### ISSUE TITLE
Loading images on AGM maps

### ISSUE THREAD

**Issue by uttamchaturvedi9** [AckerApple/agm-overlays#49] opened 2020-11-05 17:25 UTC
I have one requirement to show/hide images on google map using agm something as shown below. I think there is some utility is available with AGM, however i am not aware of it.Below is my code to load map and on handleOnTilesLoaded() method I would like to add some code to load images.
<agm-map [zoom]="5" [latitude]="lat" [longitude]="lng" (mapReady)="onMapReady($event)"
(mapClick)="mapClick($event)" (mapReady)="mapReady($event)"(tilesLoaded)="handleOnTilesLoaded()">
![2020-11-03_19h21_17](https://user-images.githubusercontent.com/29146996/98274900-4b11a300-1f94-11eb-8ed6-f6b86c5775eb.png)

**Comment by AckerApple** [comment] 2020-11-05 17:33
Duplicate of #48

**Closed as completed** 2020-11-06 02:48 UTC
Labels: duplicate
